### ISSUE TITLE
Input Output file bugs

### ISSUE THREAD

**Issue by Ank1taS** [Blaze-Stars/Image-Filter-Application#59]
Found the Following 4 possible bugs (till now) while passing I/O file(s) in the command line:
- When the `Input file is a .BMP file` but the `output file is not a .BMP file`, the application executes without resulting in any error message.

![notbmpout](https://user-images.githubusercontent.com/65461370/177376201-6b25b641-9cc2-41c3-a3f8-cade71ccfcb3.png)
   

- When `Input file is an exiting non .BMP file`,  the application terminates but not with an appropriate error message however it should happen before promoting the option to the user.

![Screenshot_2022-07-05_22-15-12](https://user-images.githubusercontent.com/65461370/177376833-dbd25ea7-b9bb-48d0-9c2a-92c694f1308e.png)

-  When `Both the input and output files are not .BMP files`, the application executes without resulting in any error message.  

![bothnotBMP](https://user-images.githubusercontent.com/65461370/177376137-44ed6b69-251e-4d39-93c3-6b4ca7228aec.png)

- When `Input and Output file both are the same file`, the application terminates but not with an appropriate error massage however it should happen before promoting the option to the user.

![sameBMP](https://user-images.githubusercontent.com/65461370/177376256-40849eee-d804-4fad-bc1e-85c419bc282f.png)

**Comment by Himanshu40** [comment]
@chandrakant100 These bugs need to be fixed since it can drive the application in another way instead of the right direction.
